### ISSUE TITLE
Change startup message

### ISSUE THREAD

**Issue by MeladTheBad** [Bleuzen/Blizcord#18] opened 2019-08-17 02:25 UTC
How to customize the start up message ? 
![image](https://user-images.githubusercontent.com/42744111/63205596-cfd67f80-c0b7-11e9-8b17-fe771a5faeb4.png)

**Comment by MeladTheBad** [comment] 2019-08-17 02:26
![image](https://user-images.githubusercontent.com/42744111/63205601-e8469a00-c0b7-11e9-81c3-23cd0e7dd9bf.png)
The yellow highlighted part in particular, I wish to customize to display the message in a different language other than English

**Comment by Bleuzen** [comment] 2019-08-17 10:48
Hi, only the startup message? There are other messages also in english, I think it wouldn't make sense to make only one of them translatable.

Well, I'm sorry, but currently there is no translation system built in.

I will keep this open as an idea for the future.

**Comment by Bleuzen** [comment] 2019-08-17 10:49
Seems like a duplicate of
https://github.com/Bleuzen/Blizcord/issues/11

**Closed** 2019-08-17 10:50 UTC
Labels: duplicate, enhancement
